const EARTH_RADIUS = 6371
const FARE_PER_KM_AIR_INDIA = 4
const FARE_PER_KM_INDIGO = 6
const FARE_PER_KM_SPICEJET = 7
const FARE_PER_KM_VISTARA = 8

module.exports = {
  EARTH_RADIUS,
  FARE_PER_KM_AIR_INDIA,
  FARE_PER_KM_INDIGO,
  FARE_PER_KM_SPICEJET,
  FARE_PER_KM_VISTARA,
}